[versions]
# The latest versions are available at https://lambdaurora.dev/tools/import_quilt.html
minecraft = "1.19.2"
quilt_loader = "0.17.5"

qsl = "3.0.0-beta.20"
groovyduvet = "1.1.0"

mdg_dsl = "1.1.3"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

qsl = { module = "org.quiltmc:qsl", version.ref = "qsl" }
groovyduvet_all = { module = "io.github.lukebemish.groovyduvet:groovyduvet", version.ref = "groovyduvet" }
groovyduvet_groovy = { module = "io.github.lukebemish.groovyduvet:groovyduvet-groovy", version.ref = "groovyduvet" }

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version = "1.0.+" }
mdg = { id = "io.github.groovymc.modsdotgroovy", version = "1.1.2" }
